# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from plnctrl/objInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class objInfo(genpy.Message):
  _md5sum = "d2cef7aa5802a9817bbcec1ed7df06d6"
  _type = "plnctrl/objInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16           classes
float32         posX
float32         posY
float32         posZ
float32         size
float32         distance
"""
  __slots__ = ['classes','posX','posY','posZ','size','distance']
  _slot_types = ['int16','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       classes,posX,posY,posZ,size,distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(objInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.classes is None:
        self.classes = 0
      if self.posX is None:
        self.posX = 0.
      if self.posY is None:
        self.posY = 0.
      if self.posZ is None:
        self.posZ = 0.
      if self.size is None:
        self.size = 0.
      if self.distance is None:
        self.distance = 0.
    else:
      self.classes = 0
      self.posX = 0.
      self.posY = 0.
      self.posZ = 0.
      self.size = 0.
      self.distance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_h5f().pack(_x.classes, _x.posX, _x.posY, _x.posZ, _x.size, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 22
      (_x.classes, _x.posX, _x.posY, _x.posZ, _x.size, _x.distance,) = _get_struct_h5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_h5f().pack(_x.classes, _x.posX, _x.posY, _x.posZ, _x.size, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 22
      (_x.classes, _x.posX, _x.posY, _x.posZ, _x.size, _x.distance,) = _get_struct_h5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_h5f = None
def _get_struct_h5f():
    global _struct_h5f
    if _struct_h5f is None:
        _struct_h5f = struct.Struct("<h5f")
    return _struct_h5f
