# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from plnctrl/totalInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class totalInfo(genpy.Message):
  _md5sum = "307b323c71a6beac17cb6e2b5ec8260e"
  _type = "plnctrl/totalInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 	State
bool 	isStop
float32 Speed
float32 Yaw
"""
  __slots__ = ['State','isStop','Speed','Yaw']
  _slot_types = ['int32','bool','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       State,isStop,Speed,Yaw

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(totalInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.State is None:
        self.State = 0
      if self.isStop is None:
        self.isStop = False
      if self.Speed is None:
        self.Speed = 0.
      if self.Yaw is None:
        self.Yaw = 0.
    else:
      self.State = 0
      self.isStop = False
      self.Speed = 0.
      self.Yaw = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_iB2f().pack(_x.State, _x.isStop, _x.Speed, _x.Yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.State, _x.isStop, _x.Speed, _x.Yaw,) = _get_struct_iB2f().unpack(str[start:end])
      self.isStop = bool(self.isStop)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_iB2f().pack(_x.State, _x.isStop, _x.Speed, _x.Yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.State, _x.isStop, _x.Speed, _x.Yaw,) = _get_struct_iB2f().unpack(str[start:end])
      self.isStop = bool(self.isStop)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_iB2f = None
def _get_struct_iB2f():
    global _struct_iB2f
    if _struct_iB2f is None:
        _struct_iB2f = struct.Struct("<iB2f")
    return _struct_iB2f
