# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from test_pkg/test_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class test_msg(genpy.Message):
  _md5sum = "dee99328feda92f62e13175df4bb1f06"
  _type = "test_pkg/test_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 data_a
float32 data_b
float64 data_c
"""
  __slots__ = ['data_a','data_b','data_c']
  _slot_types = ['int16','float32','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       data_a,data_b,data_c

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(test_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.data_a is None:
        self.data_a = 0
      if self.data_b is None:
        self.data_b = 0.
      if self.data_c is None:
        self.data_c = 0.
    else:
      self.data_a = 0
      self.data_b = 0.
      self.data_c = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_hfd().pack(_x.data_a, _x.data_b, _x.data_c))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.data_a, _x.data_b, _x.data_c,) = _get_struct_hfd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_hfd().pack(_x.data_a, _x.data_b, _x.data_c))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.data_a, _x.data_b, _x.data_c,) = _get_struct_hfd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_hfd = None
def _get_struct_hfd():
    global _struct_hfd
    if _struct_hfd is None:
        _struct_hfd = struct.Struct("<hfd")
    return _struct_hfd
