// Generated by gencpp from file morai_tutorial/test_msg.msg
// DO NOT EDIT!


#ifndef MORAI_TUTORIAL_MESSAGE_TEST_MSG_H
#define MORAI_TUTORIAL_MESSAGE_TEST_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morai_tutorial
{
template <class ContainerAllocator>
struct test_msg_
{
  typedef test_msg_<ContainerAllocator> Type;

  test_msg_()
    : data_a(0)
    , data_b(0)
    , data_c(0)  {
    }
  test_msg_(const ContainerAllocator& _alloc)
    : data_a(0)
    , data_b(0)
    , data_c(0)  {
  (void)_alloc;
    }



   typedef int16_t _data_a_type;
  _data_a_type data_a;

   typedef int16_t _data_b_type;
  _data_b_type data_b;

   typedef int16_t _data_c_type;
  _data_c_type data_c;





  typedef boost::shared_ptr< ::morai_tutorial::test_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_tutorial::test_msg_<ContainerAllocator> const> ConstPtr;

}; // struct test_msg_

typedef ::morai_tutorial::test_msg_<std::allocator<void> > test_msg;

typedef boost::shared_ptr< ::morai_tutorial::test_msg > test_msgPtr;
typedef boost::shared_ptr< ::morai_tutorial::test_msg const> test_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_tutorial::test_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_tutorial::test_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_tutorial::test_msg_<ContainerAllocator1> & lhs, const ::morai_tutorial::test_msg_<ContainerAllocator2> & rhs)
{
  return lhs.data_a == rhs.data_a &&
    lhs.data_b == rhs.data_b &&
    lhs.data_c == rhs.data_c;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_tutorial::test_msg_<ContainerAllocator1> & lhs, const ::morai_tutorial::test_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_tutorial::test_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_tutorial::test_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_tutorial::test_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_tutorial::test_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_tutorial::test_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_tutorial::test_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_tutorial::test_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36b5034dc307de7513c892457d2121f8";
  }

  static const char* value(const ::morai_tutorial::test_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36b5034dc307de75ULL;
  static const uint64_t static_value2 = 0x13c892457d2121f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_tutorial::test_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_tutorial/test_msg";
  }

  static const char* value(const ::morai_tutorial::test_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_tutorial::test_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 data_a\n"
"int16 data_b\n"
"int16 data_c\n"
"\n"
;
  }

  static const char* value(const ::morai_tutorial::test_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_tutorial::test_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data_a);
      stream.next(m.data_b);
      stream.next(m.data_c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct test_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_tutorial::test_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_tutorial::test_msg_<ContainerAllocator>& v)
  {
    s << indent << "data_a: ";
    Printer<int16_t>::stream(s, indent + "  ", v.data_a);
    s << indent << "data_b: ";
    Printer<int16_t>::stream(s, indent + "  ", v.data_b);
    s << indent << "data_c: ";
    Printer<int16_t>::stream(s, indent + "  ", v.data_c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_TUTORIAL_MESSAGE_TEST_MSG_H
