// Generated by gencpp from file plnctrl/fussInfo.msg
// DO NOT EDIT!


#ifndef PLNCTRL_MESSAGE_FUSSINFO_H
#define PLNCTRL_MESSAGE_FUSSINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <plnctrl/fusInfo.h>

namespace plnctrl
{
template <class ContainerAllocator>
struct fussInfo_
{
  typedef fussInfo_<ContainerAllocator> Type;

  fussInfo_()
    : objNum(0)
    , data()  {
    }
  fussInfo_(const ContainerAllocator& _alloc)
    : objNum(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _objNum_type;
  _objNum_type objNum;

   typedef std::vector< ::plnctrl::fusInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::plnctrl::fusInfo_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::plnctrl::fussInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plnctrl::fussInfo_<ContainerAllocator> const> ConstPtr;

}; // struct fussInfo_

typedef ::plnctrl::fussInfo_<std::allocator<void> > fussInfo;

typedef boost::shared_ptr< ::plnctrl::fussInfo > fussInfoPtr;
typedef boost::shared_ptr< ::plnctrl::fussInfo const> fussInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plnctrl::fussInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plnctrl::fussInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plnctrl::fussInfo_<ContainerAllocator1> & lhs, const ::plnctrl::fussInfo_<ContainerAllocator2> & rhs)
{
  return lhs.objNum == rhs.objNum &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plnctrl::fussInfo_<ContainerAllocator1> & lhs, const ::plnctrl::fussInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plnctrl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::plnctrl::fussInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plnctrl::fussInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plnctrl::fussInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plnctrl::fussInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plnctrl::fussInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plnctrl::fussInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plnctrl::fussInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80f20e09e9bf88e655f5e38cccf2953f";
  }

  static const char* value(const ::plnctrl::fussInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80f20e09e9bf88e6ULL;
  static const uint64_t static_value2 = 0x55f5e38cccf2953fULL;
};

template<class ContainerAllocator>
struct DataType< ::plnctrl::fussInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plnctrl/fussInfo";
  }

  static const char* value(const ::plnctrl::fussInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plnctrl::fussInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16       objNum\n"
"fusInfo[]   data\n"
"\n"
"================================================================================\n"
"MSG: plnctrl/fusInfo\n"
"int32           classes\n"
"float32         posX\n"
"float32         posY\n"
"float32         posZ\n"
"float32         size\n"
"float32         distance\n"
;
  }

  static const char* value(const ::plnctrl::fussInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plnctrl::fussInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objNum);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fussInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plnctrl::fussInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plnctrl::fussInfo_<ContainerAllocator>& v)
  {
    s << indent << "objNum: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.objNum);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::plnctrl::fusInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLNCTRL_MESSAGE_FUSSINFO_H
