// Generated by gencpp from file plnctrl/GNSSInfo.msg
// DO NOT EDIT!


#ifndef PLNCTRL_MESSAGE_GNSSINFO_H
#define PLNCTRL_MESSAGE_GNSSINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plnctrl
{
template <class ContainerAllocator>
struct GNSSInfo_
{
  typedef GNSSInfo_<ContainerAllocator> Type;

  GNSSInfo_()
    : heading(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)  {
    }
  GNSSInfo_(const ContainerAllocator& _alloc)
    : heading(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)  {
  (void)_alloc;
    }



   typedef float _heading_type;
  _heading_type heading;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;





  typedef boost::shared_ptr< ::plnctrl::GNSSInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plnctrl::GNSSInfo_<ContainerAllocator> const> ConstPtr;

}; // struct GNSSInfo_

typedef ::plnctrl::GNSSInfo_<std::allocator<void> > GNSSInfo;

typedef boost::shared_ptr< ::plnctrl::GNSSInfo > GNSSInfoPtr;
typedef boost::shared_ptr< ::plnctrl::GNSSInfo const> GNSSInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plnctrl::GNSSInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plnctrl::GNSSInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plnctrl::GNSSInfo_<ContainerAllocator1> & lhs, const ::plnctrl::GNSSInfo_<ContainerAllocator2> & rhs)
{
  return lhs.heading == rhs.heading &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.altitude == rhs.altitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plnctrl::GNSSInfo_<ContainerAllocator1> & lhs, const ::plnctrl::GNSSInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plnctrl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::plnctrl::GNSSInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plnctrl::GNSSInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plnctrl::GNSSInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plnctrl::GNSSInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plnctrl::GNSSInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plnctrl::GNSSInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plnctrl::GNSSInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d7430197e46d53fe663cf5d6b910d2b";
  }

  static const char* value(const ::plnctrl::GNSSInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d7430197e46d53fULL;
  static const uint64_t static_value2 = 0xe663cf5d6b910d2bULL;
};

template<class ContainerAllocator>
struct DataType< ::plnctrl::GNSSInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plnctrl/GNSSInfo";
  }

  static const char* value(const ::plnctrl::GNSSInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plnctrl::GNSSInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32     heading\n"
"float64     latitude\n"
"float64     longitude\n"
"float64     altitude\n"
;
  }

  static const char* value(const ::plnctrl::GNSSInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plnctrl::GNSSInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GNSSInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plnctrl::GNSSInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plnctrl::GNSSInfo_<ContainerAllocator>& v)
  {
    s << indent << "heading: ";
    Printer<float>::stream(s, indent + "  ", v.heading);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLNCTRL_MESSAGE_GNSSINFO_H
